### ISSUE TITLE
Self closing tags

### ISSUE THREAD

**Issue by ptrdvds** [syrusakbary/pyjade#186]
Self closing tags do not work.

I tried:
```
      embed(src="foo")/
```
to render to:
```
      <embed src="foo"/>
```
but it does (which is wrong):
```
      <embed src="foo"></embed>/
```

Will this be supported?

**Comment by blx** [comment]
There's a couple things here:

1. `embed` is partially (or additionally) a different problem, because in html5 it's [supposed to be](http://www.w3.org/TR/html5/embedded-content-0.html#the-embed-element) self-closing anyway. Jade(JS) uses [void-elements](https://github.com/jadejs/void-elements/blob/master/index.js) to determine if a tag *should* self-close, and their list includes `embed`, while [PyJade's doesn't](https://github.com/syrusakbary/pyjade/blob/master/pyjade/compiler.py#L40) right now. That's just a matter of changing the list of self-closing tags.

2. But self-closing for arbitrary tags doesn't work, you're right.
    Strangely, I'm getting
    ```
        <foo>/</foo>
    ```
    instead of your example of
    ```
        <foo></foo>/
    ```
    given the jade source of
    ```
        foo/
    ```
    Jade(JS) gives the expected output of
    ```
        <foo/>
    ```
3. I hacked together a semi-fix for this in the compiler, but it really belongs in the lexer, I think, and I'm not totally sure where exactly.

**Comment by syrusakbary** [comment]
Your fix in the lexer should work too!
I will merge the pull request once you have it :)
