### ISSUE TITLE
Returning "None" when calling a variable

### ISSUE THREAD

**Issue by emiguelt** [syrusakbary/pyjade#220]
Hi!
I'm a newbie in python. I'm working on a console application that generates a basic xml file, so I decided to use PyJade because of my preview experience with Jade.

The code is as follows:

```python
from pyjade.utils import process
import os
...
f = open('templates/genoutdaily.proj.jade', 'r')
prj = open('../out/genoutdaily.proj', 'w')
obj = {'name': 'test'}
prj.write(process(f.read(), **obj))
f.close()
prj.close()
...
```

The template:
```jade
person
  name #{name}
```
and the output
```xml
<person>
  <name>None</name>
</person>
```

I don't know why I'm getting ```None``` instead of ```test```

Could somebody help me?

Thanks in advance,

Edwin

**Comment by blx** [comment]
Hi Edwin!

This isn't your fault, the problem is that PyJade was initially intended to just translate Jade templates into other template languages (like Django templates) and let them do the variable interpolation and so on. The builtin PyJade HTML/XML compiler came later, and right now `pyjade.utils.process()` doesn't pass along any variable context to the compiler.

You have a few options. One is to also install a template library like `jinja2` that PyJade can convert into -- [here is an example of that](https://github.com/syrusakbary/pyjade/issues/136#issuecomment-131724973), it's a pretty smooth process.

Another way is to patch the built-in `process()` function to accept variables.

I'm working on improvements, but in the meantime you can use the following function instead of `pyjade.utils.process()`:
```python
from pyjade.parser import Parser
from pyjade.ext.html import HTMLCompiler, local_context_manager

def process(jade_string, context=None, **compiler_kwargs):
    ctx = context or {}
    block = Parser(jade_string).parse()
    compiler = HTMLCompiler(block, **compiler_kwargs)
    with local_context_manager(compiler, ctx):
        return compiler.compile()

# So your code becomes
with open('templates/genoutdaily.proj.jade') as f:
    with open('../out/genoutdaily.proj', 'w') as prj:
        obj = {'name': 'test'}
        prj.write(process(f.read(), obj))
# and no file-closing needed, because `with` takes care of that when you leave the block
```

**Comment by emiguelt** [comment]
Hi Ben!
Thanks a lot for your response!
The code you sent me worked perfectly!

Best,

Edwin
